# Generated by Django 5.2.4 on 2025-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('article_url', models.URLField(max_length=1000)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('agency', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Regulatory Intelligence Data',
                'verbose_name_plural': 'Regulatory Intelligence Data',
                'ordering': ['-date'],
            },
        ),
    ]
