# Generated by Django 5.2.4 on 2025-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydata',
            name='drug_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
