# Generated by Django 5.2.4 on 2025-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_app', '0002_regulatorydata_drug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydata',
            name='document_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regulatorydata',
            name='product_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
