# Generated by Django 5.2.4 on 2025-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_app', '0003_regulatorydata_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulatorydata',
            old_name='document_type',
            new_name='Document_Type',
        ),
        migrations.RenameField(
            model_name='regulatorydata',
            old_name='product_type',
            new_name='Drug_names',
        ),
        migrations.RemoveField(
            model_name='regulatorydata',
            name='drug_name',
        ),
        migrations.AddField(
            model_name='regulatorydata',
            name='Product_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
