# Generated by Django 5.2.4 on 2025-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri_app', '0004_rename_document_type_regulatorydata_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydata',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
